[project]
name = "polynx"
version = "0.1.0"
description = "String-powered Polars expression engine with extended DataFrame utilities"
authors = [
  { name="Lowell Winston", email="lowell.j.winston@gmail.com" }
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11.1"
dependencies = [
  "polars>=1.24",
  "lark>=1.2.2",
  "matplotlib>=3.8.2",
  "pandas>=2.1.4",
  "numpy>=1.26.2",
  "re>=2.2.1",
  "inspect"
]

[project.urls]
Homepage = "https://github.com/LowellWinston/polynx.git"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
