from setuptools import setup, find_packages

setup(
    name="polynx",  
    version="0.1.20",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    package_data={"polynx": ["py.typed", "AGENTS.md"]},
    install_requires=[  
        "polars>=1.8",
        "lark>=1.2.2",
        "matplotlib>=3.7",
        "pandas>=2.0.0",
        "numpy>=1.24",
        "pyarrow>=10.0.0",
    ],
    python_requires=">=3.9",
    author='Lowell Winston',
    author_email='lowell.j.winston@gmail.com',
    description='String-powered Polars expression engine with extended DataFrame utilities.',
    keywords=['polars', 'dataframe', 'query', 'expression', 'string-expression', 'pandas-like', 'llm', 'ai-agents'],
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/LowellWinston/polynx",  
    classifiers=[
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    project_urls={
        'Documentation': 'https://lowellwinston.github.io/polynx/',
        'Changelog': 'https://github.com/LowellWinston/polynx/blob/master/CHANGELOG.md',
        'Source': 'https://github.com/LowellWinston/polynx',
        'Agent Guide': 'https://github.com/LowellWinston/polynx/blob/master/src/polynx/AGENTS.md',
    },
)
